2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_setup.py:_flush():76] Configure stats pid to 22948
2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_setup.py:_flush():76] Loading settings from C:\Users\24871\.config\wandb\settings
2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_setup.py:_flush():76] Loading settings from E:\Code\Kaggle\wandb\settings
2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True', 'mode': 'online', 'api_key': '***REDACTED***'}
2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'E:\\Code\\Kaggle\\train.py'}
2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_init.py:_log_setup():461] Logging user logs to E:\Code\Kaggle\wandb\run-20220901_221340-203zrsna\logs\debug.log
2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_init.py:_log_setup():462] Logging internal logs to E:\Code\Kaggle\wandb\run-20220901_221340-203zrsna\logs\debug-internal.log
2022-09-01 22:13:40,004 INFO    MainThread:22948 [wandb_init.py:init():495] calling init triggers
2022-09-01 22:13:40,005 INFO    MainThread:22948 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2022-09-01 22:13:40,005 INFO    MainThread:22948 [wandb_init.py:init():548] starting backend
2022-09-01 22:13:40,005 INFO    MainThread:22948 [wandb_init.py:init():552] setting up manager
2022-09-01 22:13:40,007 INFO    MainThread:22948 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-09-01 22:13:40,009 INFO    MainThread:22948 [wandb_init.py:init():558] backend started and connected
2022-09-01 22:13:40,010 INFO    MainThread:22948 [wandb_init.py:init():636] updated telemetry
2022-09-01 22:13:40,065 INFO    MainThread:22948 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2022-09-01 22:13:46,163 WARNING MsgRouterThr:22948 [router.py:message_loop():76] message_loop has been closed
2022-09-01 22:14:10,075 INFO    MainThread:22948 [interface_shared.py:_communicate_run():331] couldn't get run from backend
2022-09-01 22:14:10,075 ERROR   MainThread:22948 [wandb_init.py:init():676] backend process timed out
2022-09-01 22:14:10,075 ERROR   MainThread:22948 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
